// Reads static JSON generated by GitHub Actions and renders the next home game.
const PT = 'America/Los_Angeles';
const statusEl = document.getElementById('status');
const loadingEl = document.getElementById('loading');
const errorEl = document.getElementById('error');
const gameEl = document.getElementById('game');
const noGamesEl = document.getElementById('no-games');

const opponentEl = document.getElementById('opponent');
const datetimeEl = document.getElementById('datetime');
const countdownEl = document.getElementById('countdown');

function fmtDateTime(iso) {
  const d = new Date(iso);
  const datePart = new Intl.DateTimeFormat('en-US', { timeZone: PT, weekday:'short', month:'short', day:'numeric', year:'numeric' }).format(d);
  const timePart = new Intl.DateTimeFormat('en-US', { timeZone: PT, hour:'numeric', minute:'2-digit' }).format(d);
  return `${datePart} • ${timePart} PT`;
}

function startCountdown(iso) {
  const target = new Date(iso).getTime();
  function tick() {
    const now = Date.now();
    let diff = Math.max(0, target - now);
    const ds = Math.floor(diff / 86400000); diff -= ds*86400000;
    const hs = Math.floor(diff / 3600000); diff -= hs*3600000;
    const ms = Math.floor(diff / 60000); diff -= ms*60000;
    const ss = Math.floor(diff / 1000);
    countdownEl.textContent = `${ds}d ${hs}h ${ms}m ${ss}s`;
  }
  tick();
  return setInterval(tick, 1000);
}

async function main() {
  try {
    const res = await fetch('data/games.json', { cache: 'no-store' });
    if (!res.ok) throw new Error(`Failed to load data/games.json (${res.status})`);
    const data = await res.json();

    // Find first home game with start >= now
    const now = Date.now();
    const upcoming = (data.homeGames || []).filter(g => new Date(g.datetime || `${g.date}T00:00:00Z`).getTime() >= now);
    if (!upcoming.length) {
      loadingEl.classList.add('hidden');
      noGamesEl.classList.remove('hidden');
      return;
    }

    const next = upcoming[0];
    const tipISO = next.datetime || `${next.date}T00:00:00Z`;
    opponentEl.textContent = `${next.opponent} @ Clippers`;
    datetimeEl.textContent = fmtDateTime(tipISO);

    loadingEl.classList.add('hidden');
    gameEl.classList.remove('hidden');

    // Start countdown
    startCountdown(tipISO);
  } catch (err) {
    loadingEl.classList.add('hidden');
    errorEl.textContent = `Error: ${err.message || err}`;
    errorEl.classList.remove('hidden');
  }
}
main();
