name: Update Clippers Home Games

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * *"  # daily at 12:00 UTC (5:00 AM PT during PDT)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate games.json
        run: node scripts/fetch_games.mjs
        env:
          BALLDONTLIE_API_KEY: ${{ secrets.BALLDONTLIE_API_KEY }}

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update games.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
